# Generated by Django 3.1.6 on 2021-02-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tast',
            new_name='Task',
        ),
    ]
